version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:

    build: .
    container_name: my_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata:
